spring:
  application:
    name: journal application
  data:
    mongodb:
      uri: mongodb+srv://kumarpriyansh2018:QTj2HNsaXghlwfdX@cluster0.wf0ru.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kumar.priyansh2018@gmail.com
    password: **** **** **** ****
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081