package com.journal.proj.scheduler;


import com.journal.proj.Entity.journalEntity;
import com.journal.proj.Entity.userEntity;
import com.journal.proj.api.response.sentimentResponse;
import com.journal.proj.service.emailService;
import com.journal.proj.service.sentimentAnalysisService;
import com.journal.proj.service.userService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.stream.Collectors;

@Component
public class userMailScheduler {

    @Autowired
    private emailService emailservice;

    @Autowired
    private userService userservice;

    @Autowired
    private sentimentAnalysisService sentimentservice;


//    @Scheduled(cron = "0 0 9 * * SUN")
//    @Scheduled(cron = "0 * * ? * *")

    public sentimentResponse fetchUserAndSendMail(){
        List<userEntity> userForSA = userservice.getUsetForSA();
        for(userEntity user:userForSA){
            List<journalEntity> journalentries = user.getJournalentries();
            List<String> collect_journal = journalentries.stream().filter(x -> x.getDate().isAfter(LocalDateTime.now().minus(7, ChronoUnit.DAYS))).map(x -> x.getContent()).collect(Collectors.toList());
           String joinedJournal = String.join(",",collect_journal);
           sentimentResponse sentiment = sentimentservice.getSentiment(joinedJournal);
           emailservice.sendEmail(user.getEmail(),"This is an autogenerated mail","Hi.You felt " + sentiment.getSentiment());
            return sentiment;
        }

        return null;

    }
}
